version: "3.3"

services:
  server:
    build: server/
    
    command: python ./server.py
    ports:
      - 3011:3001
    networks:
      - default
      
  client:
    build: client/
    
    command: python ./client.py
    networks:
      - default
    depends_on:
      - server